apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: moco
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  project: default
  source:
    repoURL: https://github.com/cybozu-go/neco-apps.git
    targetRevision: release
    path: moco/base
  destination:
    server: https://kubernetes.default.svc
    namespace: moco-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
