apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: kube-system/neco-admission
  creationTimestamp: null
webhooks:
- name: mhttpproxy.kb.io
  clientConfig:
    service:
      name: neco-admission
      namespace: kube-system
- name: mpod.kb.io
  clientConfig:
    service:
      name: neco-admission
      namespace: kube-system
  namespaceSelector:
    matchExpressions:
    - key: admission.cybozu.com/pod
      operator: NotIn
      values:
      - ignore
  objectSelector:
    matchExpressions:
    - key: app.kubernetes.io/name
      operator: NotIn
      values:
      - neco-admission
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: kube-system/neco-admission
  creationTimestamp: null
webhooks:
- name: vhttpproxy.kb.io
  clientConfig:
    service:
      name: neco-admission
      namespace: kube-system
- name: vnetworkpolicy.kb.io
  clientConfig:
    service:
      name: neco-admission
      namespace: kube-system
  namespaceSelector:
    matchExpressions:
    - key: vnetworkpolicy.kb.io/ignore
      operator: NotIn
      values:
      - "true"
- name: vapplication.kb.io
  clientConfig:
    service:
      name: neco-admission
      namespace: kube-system
- name: vdelete.kb.io
  clientConfig:
    service:
      name: neco-admission
      namespace: kube-system
  matchPolicy: Equivalent
  # According to this code https://github.com/kubernetes-sigs/controller-tools/blob/master/pkg/webhook/parser.go#L183,
  # `rules` cannot be generated with multiple GVK, so we should add new GVK manually here.
  rules:
  - apiGroups:
    - apiextensions.k8s.io
    apiVersions:
    - v1
    - v1beta1
    operations:
    - DELETE
    resources:
    - customresourcedefinitions
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - DELETE
    resources:
    - namespaces
  - apiGroups:
    - ceph.rook.io
    apiVersions:
    - v1
    operations:
    - DELETE
    resources:
    - cephblockpools
    - cephclusters
    - cephobjectstores
- name: vgrafanadashboard.kb.io
  clientConfig:
    service:
      name: neco-admission
      namespace: kube-system
  matchPolicy: Equivalent
- name: vpod.kb.io
  clientConfig:
    service:
      name: neco-admission
      namespace: kube-system
  matchPolicy: Equivalent
  namespaceSelector:
    matchExpressions:
    - key: admission.cybozu.com/pod
      operator: NotIn
      values:
      - ignore
- name: vpreventdelete.kb.io
  clientConfig:
    service:
      name: neco-admission
      namespace: kube-system
  matchPolicy: Equivalent
  # According to this code https://github.com/kubernetes-sigs/controller-tools/blob/master/pkg/webhook/parser.go#L183,
  # `rules` cannot be generated with multiple GVK, so we should add new GVK manually here.
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - DELETE
    resources:
    - persistentvolumeclaims
  - apiGroups:
    - objectbucket.io
    apiVersions:
    - v1alpha1
    operations:
    - DELETE
    resources:
    - objectbucketclaims
  - apiGroups:
    - moco.cybozu.com
    apiVersions:
    - v1alpha1
    operations:
    - DELETE
    resources:
    - mysqlclusters
  - apiGroups:
    - elasticsearch.k8s.elastic.co
    apiVersions:
    - v1beta1
    operations:
    - DELETE
    resources:
    - elasticsearches
- name: vservice.kb.io
  clientConfig:
    service:
      name: neco-admission
      namespace: kube-system
  matchPolicy: Equivalent
