apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - upstream/crd
  - upstream/rbac/vmagent_editor_role.yaml
  - upstream/rbac/vmagent_viewer_role.yaml
  - upstream/rbac/vmalert_editor_role.yaml
  - upstream/rbac/vmalert_viewer_role.yaml
  - upstream/rbac/vmalertmanager_editor_role.yaml
  - upstream/rbac/vmalertmanager_viewer_role.yaml
  - upstream/rbac/vmpodscrape_editor_role.yaml
  - upstream/rbac/vmpodscrape_viewer_role.yaml
  - upstream/rbac/vmprobe_editor_role.yaml
  - upstream/rbac/vmprobe_viewer_role.yaml
  - upstream/rbac/vmrule_editor_role.yaml
  - upstream/rbac/vmrule_viewer_role.yaml
  - upstream/rbac/vmservicescrape_editor_role.yaml
  - upstream/rbac/vmservicescrape_viewer_role.yaml
  - rbac
  - operator.yaml
  - configmap-settype.yaml
  - vmalertmanager-smallset.yaml
  - vmagent-smallset.yaml
  - vmalert-smallset.yaml
  - vmsingle-smallset.yaml
  - vmalertmanager-largeset.yaml
  - vmagent-largeset.yaml
  - vmalert-largeset.yaml
  - vmcluster-largeset.yaml
  - rules/argocd-alertrule.yaml
  - rules/argocd-scrape.yaml
  - rules/cert-manager-alertrule.yaml
  - rules/cert-manager-scrape.yaml
  - rules/cke-alertrule.yaml
  - rules/cke-scrape.yaml
  - rules/coil-scrape.yaml
  - rules/elastic-operator-alertrule.yaml
  - rules/elastic-operator-scrape.yaml
  - rules/etcd-alertrule.yaml
  - rules/etcd-scrape.yaml
  - rules/external-dns-alertrule.yaml
  - rules/external-dns-scrape.yaml
  - rules/ingress-alertrule.yaml
  - rules/ingress-scrape.yaml
  - rules/ingress-watcher-alertrule.yaml
  - rules/kube-state-metrics-scrape.yaml
  - rules/kube-state-metrics-alertrule.yaml
  - rules/kubernetes-scrape.yaml
  - rules/kubernetes-alertrule.yaml
  - rules/local-pv-provisioner-scrape.yaml
  - rules/metallb-alertrule.yaml
  - rules/metallb-scrape.yaml
  - rules/monitoring-scrape.yaml
  - rules/monitoring-alertrule.yaml
  - rules/neco-admission-alertrule.yaml
  - rules/neco-admission-scrape.yaml
  - rules/network-policy-alertrule.yaml
  - rules/network-policy-scrape.yaml
  - rules/node-alertrule.yaml
  - rules/node-scrape.yaml
  - rules/rook-scrape.yaml
  - rules/rook-alertrule.yaml
  - rules/sabakan-alertrule.yaml
  - rules/sabakan-scrape.yaml
  - rules/teleport-alertrule.yaml
  - rules/teleport-scrape.yaml
  - rules/topolvm-scrape.yaml
  - rules/vault-alertrule.yaml
  - rules/vault-scrape.yaml
patchesStrategicMerge:
  - remove_crd_status.yaml
  - rbac/viewer_aggregation.yaml
  - rbac/editor_aggregation.yaml
configMapGenerator:
  - name: vmalertmanager
    files:
      - neco.template
configurations:
- kustomizeconfig.yaml
