apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent-largeset
  namespace: monitoring
spec:
  serviceScrapeSelector:
    matchExpressions:
      - key: managed-by
        operator: NotIn
        values:
          - vm-operator
  podScrapeSelector:
    matchExpressions:
      - key: managed-by
        operator: NotIn
        values:
          - vm-operator
  nodeScrapeSelector:
    matchExpressions:
      - key: managed-by
        operator: NotIn
        values:
          - vm-operator
  probeSelector:
    matchExpressions:
      - key: managed-by
        operator: NotIn
        values:
          - vm-operator
  replicaCount: 3
  remoteWrite:
    - url: "http://vminsert-vmcluster-largeset.monitoring.svc:8480/insert/0/prometheus/api/v1/write"
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/component: monitoring
          app.kubernetes.io/instance: vmagent-largeset
          app.kubernetes.io/name: vmagent
          managed-by: vm-operator
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: vmagent-largeset
  namespace: monitoring
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: monitoring
      app.kubernetes.io/instance: vmagent-largeset
      app.kubernetes.io/name: vmagent
      managed-by: vm-operator
