apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent-smallset
  namespace: monitoring
spec:
  serviceScrapeSelector:
    matchLabels:
      smallset: "true"
  podScrapeSelector:
    matchLabels:
      smallset: "true"
  nodeScrapeSelector:
    matchLabels:
      smallset: "true"
  probeSelector:
    matchLabels:
      smallset: "true"
  replicaCount: 1
  remoteWrite:
    - url: "http://vmsingle-vmsingle-smallset.monitoring.svc:8429/api/v1/write"
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
