apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: victoriametrics-operator
  namespace: monitoring
  labels:
    smallset: "true"
spec:
  namespaceSelector:
    matchNames: [monitoring]
  selector:
    matchLabels:
      control-plane: victoriametrics-operator
  podMetricsEndpoints:
  - port: http
    relabelConfigs:
      - replacement: victoriametrics-operator
        targetLabel: job
      - sourceLabels: [__meta_kubernetes_pod_container_name]
        regex: manager
        action: keep
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: vmalertmanager
  namespace: monitoring
  labels:
    smallset: "true"
spec:
  namespaceSelector:
    matchNames: [monitoring]
  selector:
    matchLabels:
      app.kubernetes.io/component: monitoring
      app.kubernetes.io/instance: vmalertmanager
      app.kubernetes.io/name: vmalertmanager
      managed-by: vm-operator
  endpoints:
  - port: web
    relabelConfigs:
      - replacement: vmalertmanager
        targetLabel: job
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: vmagent-smallset
  namespace: monitoring
  labels:
    smallset: "true"
spec:
  namespaceSelector:
    matchNames: [monitoring]
  selector:
    matchLabels:
      app.kubernetes.io/component: monitoring
      app.kubernetes.io/instance: vmagent-smallset
      app.kubernetes.io/name: vmagent
      managed-by: vm-operator
  endpoints:
  - port: http
    relabelConfigs:
      - replacement: vmagent-smallset
        targetLabel: job
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: vmalert-smallset
  namespace: monitoring
  labels:
    smallset: "true"
spec:
  namespaceSelector:
    matchNames: [monitoring]
  selector:
    matchLabels:
      app.kubernetes.io/component: monitoring
      app.kubernetes.io/instance: vmalert-smallset
      app.kubernetes.io/name: vmalert
      managed-by: vm-operator
  endpoints:
  - port: http
    relabelConfigs:
      - replacement: vmalert-smallset
        targetLabel: job
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: vmsingle-smallset
  namespace: monitoring
  labels:
    smallset: "true"
spec:
  namespaceSelector:
    matchNames: [monitoring]
  selector:
    matchLabels:
      app.kubernetes.io/component: monitoring
      app.kubernetes.io/instance: vmsingle-smallset
      app.kubernetes.io/name: vmsingle
      managed-by: vm-operator
  endpoints:
  - port: http
    relabelConfigs:
      - replacement: vmsingle-smallset
        targetLabel: job
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: vmagent-largeset
  namespace: monitoring
  labels:
    smallset: "true"
spec:
  namespaceSelector:
    matchNames: [monitoring]
  selector:
    matchLabels:
      app.kubernetes.io/component: monitoring
      app.kubernetes.io/instance: vmagent-largeset
      app.kubernetes.io/name: vmagent
      managed-by: vm-operator
  endpoints:
  - port: http
    relabelConfigs:
      - replacement: vmagent-largeset
        targetLabel: job
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: vmalert-largeset
  namespace: monitoring
  labels:
    smallset: "true"
spec:
  namespaceSelector:
    matchNames: [monitoring]
  selector:
    matchLabels:
      app.kubernetes.io/component: monitoring
      app.kubernetes.io/instance: vmalert-largeset
      app.kubernetes.io/name: vmalert
      managed-by: vm-operator
  endpoints:
  - port: http
    relabelConfigs:
      - replacement: vmalert-largeset
        targetLabel: job
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: vminsert-largeset
  namespace: monitoring
  labels:
    smallset: "true"
spec:
  namespaceSelector:
    matchNames: [monitoring]
  selector:
    matchLabels:
      app.kubernetes.io/component: monitoring
      app.kubernetes.io/instance: vmcluster-largeset
      app.kubernetes.io/name: vminsert
      managed-by: vm-operator
  endpoints:
  - port: http
    relabelConfigs:
      - replacement: vminsert-largeset
        targetLabel: job
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: vmselect-largeset
  namespace: monitoring
  labels:
    smallset: "true"
spec:
  namespaceSelector:
    matchNames: [monitoring]
  selector:
    matchLabels:
      app.kubernetes.io/component: monitoring
      app.kubernetes.io/instance: vmcluster-largeset
      app.kubernetes.io/name: vmselect
      managed-by: vm-operator
  endpoints:
  - port: http
    relabelConfigs:
      - replacement: vmselect-largeset
        targetLabel: job
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: vmstorage-largeset
  namespace: monitoring
  labels:
    smallset: "true"
spec:
  namespaceSelector:
    matchNames: [monitoring]
  selector:
    matchLabels:
      app.kubernetes.io/component: monitoring
      app.kubernetes.io/instance: vmcluster-largeset
      app.kubernetes.io/name: vmstorage
      managed-by: vm-operator
  endpoints:
  - port: http
    relabelConfigs:
      - replacement: vmstorage-largeset
        targetLabel: job
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: prometheus
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames: [monitoring]
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
  podMetricsEndpoints:
  - relabelConfigs:
      - replacement: prometheus
        targetLabel: job
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames: [monitoring]
  selector:
    matchLabels:
      app.kubernetes.io/name: alertmanager
  podMetricsEndpoints:
  - relabelConfigs:
      - replacement: alertmanager
        targetLabel: job
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: pushgateway
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames: [monitoring]
  selector:
    matchLabels:
      app.kubernetes.io/name: pushgateway
  podMetricsEndpoints:
  - honorLabels: true
    relabelConfigs:
      - replacement: pushgateway
        targetLabel: job
