apiVersion: v1
kind: Namespace
metadata:
  name: app-garoon-static
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: garoon-role-binding
  namespace: app-garoon-static
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: Group
    name: garoon
    apiGroup: rbac.authorization.k8s.io
  - kind: Group
    name: maneki
    apiGroup: rbac.authorization.k8s.io
