{
 "title": "Ceph - Clusters",
 "description": "Ceph Cluster overview.\r\n",
 "tags": [
  "ceph",
  "cluster"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "namespace", "label": "namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "CLUSTER STATE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max without (instance) (ceph_health_status{namespace=\"$namespace\"})",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "Write Throughput",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without (instance, ceph_daemon) (irate(ceph_osd_op_w_in_bytes{namespace=\"$namespace\"}[5m]))"
      }
     ]
    },
    {
     "title": "Read Throughput",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without (ceph_daemon, instance) (irate(ceph_osd_op_r_out_bytes{namespace=\"$namespace\"}[5m]))"
      }
     ]
    },
    {
     "title": "Cluster Capacity",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without (instance) (ceph_cluster_total_bytes{namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Available Capacity",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without (instance) ((ceph_cluster_total_bytes{namespace=\"$namespace\"}-ceph_cluster_total_used_bytes{namespace=\"$namespace\"})/ceph_cluster_total_bytes{namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Number of Objects",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without (instance, pool_id) (ceph_pool_objects{namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Bytes Written",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "delta" ] } },
     "targets": [
      {
       "expr": "sum without (instance, ceph_daemon) (ceph_osd_op_w_in_bytes{namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Bytes Read",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "delta" ] } },
     "targets": [
      {
       "expr": "sum without (instance, ceph_daemon) (ceph_osd_op_r_out_bytes{namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Alerts",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(ALERTS{namespace=\"$namespace\",alertstate='firing',alertname=~'^CephCluster.*'}) OR vector(0)"
      }
     ]
    },
    {
     "title": "Write IOPS",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without (ceph_daemon, instance) (irate(ceph_osd_op_w{namespace=\"$namespace\"}[5m]))"
      }
     ]
    },
    {
     "title": "Read IOPS",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without (ceph_daemon, instance) (irate(ceph_osd_op_r{namespace=\"$namespace\"}[5m]))"
      }
     ]
    },
    {
     "title": "Used Capacity",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without (instance) (ceph_cluster_total_used_bytes{namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Mon Session Num",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without (instance, ceph_daemon) (ceph_mon_num_sessions{namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Monitors In Quorum",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count without (instance, ceph_daemon) (ceph_mon_quorum_status{namespace=\"$namespace\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "OSD STATE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "OSDs OUT",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count without (instance, ceph_daemon) (ceph_osd_up{namespace=\"$namespace\"}) - count without (instance, ceph_daemon) (ceph_osd_in{namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "OSDs DOWN",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(ceph_osd_up{namespace=\"$namespace\"} == 0.0) OR vector(0)"
      }
     ]
    },
    {
     "title": "OSDs UP",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 4, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without (instance, ceph_daemon) (ceph_osd_up{namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "OSDs IN",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum without (instance, ceph_daemon) (ceph_osd_in{namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Avg PGs",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg without (instance, ceph_daemon) (ceph_osd_numpg{namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Avg Apply Latency",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 10, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg without (instance, ceph_daemon) (ceph_osd_apply_latency_ms{namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Avg Commit Latency",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 13, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(ceph_osd_commit_latency_ms{namespace=\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Avg Op Write Latency",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg without (instance, ceph_daemon) (rate(ceph_osd_op_w_latency_sum{namespace=\"$namespace\"}[5m]) / rate(ceph_osd_op_w_latency_count{namespace=\"$namespace\"}[5m]) >= 0)"
      }
     ]
    },
    {
     "title": "Avg  Op Read Latency",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 19, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg without (instance, ceph_daemon) (rate(ceph_osd_op_r_latency_sum{namespace=\"$namespace\"}[5m])/rate(ceph_osd_op_r_latency_count{namespace=\"$namespace\"}[5m]) >= 0)"
      }
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Alerts from CephThanos",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "ALERTS{namespace=\"$namespace\", alertstate='firing'}"
      }
     ]
    },
    {
     "title": "Top Sluggish OSD's",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
     "targets": [
      {
       "expr": "topk(5,sort_desc(ceph_osd_apply_latency_ms{namespace=\"$namespace\"} + ceph_osd_commit_latency_ms{namespace=\"$namespace\"}))"
      }
     ]
    },
    {
     "title": "Down OSD's",
     "type": "table-old",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
     "targets": [
      {
       "expr": "ceph_osd_up{namespace=\"$namespace\"} == 0"
      }
     ]
    }
   ]
  },
  {
   "title": "Ceph Versions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ceph OSD Versions",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count by (ceph_version) (ceph_osd_metadata{namespace=\"$namespace\"})",
       "legendFormat": "{{ ceph_version }}"
      }
     ]
    },
    {
     "title": "Ceph Mon Versions",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count by (ceph_version)(ceph_mon_metadata{namespace=\"$namespace\"})",
       "legendFormat": "{{ ceph_version }}"
      }
     ]
    },
    {
     "title": "Ceph MDS Versions",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count by (ceph_version)(ceph_mds_metadata{namespace=\"$namespace\"})",
       "legendFormat": "{{ ceph_version }}"
      }
     ]
    },
    {
     "title": "Ceph RGW Versions",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count by (ceph_version)(ceph_rgw_metadata{namespace=\"$namespace\"})",
       "legendFormat": "{{ ceph_version }}"
      }
     ]
    }
   ]
  },
  {
   "title": "CLUSTER",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Capacity",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum without (instance) (ceph_cluster_total_bytes{namespace=\"$namespace\"})",
       "legendFormat": "Total Capacity"
      },
      {
       "expr": "sum without (instance) (ceph_cluster_total_bytes{namespace=\"$namespace\"}-ceph_cluster_total_used_bytes{namespace=\"$namespace\"})",
       "legendFormat": "Available"
      },
      {
       "expr": "sum without (instance) (ceph_cluster_total_used_bytes{namespace=\"$namespace\"})",
       "legendFormat": "Used"
      }
     ]
    },
    {
     "title": "IOPS",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum without (instance, ceph_daemon) (irate(ceph_osd_op_w{namespace=\"$namespace\"}[5m]))",
       "legendFormat": "Write"
      },
      {
       "expr": "sum without (instance, ceph_daemon) (irate(ceph_osd_op_r{namespace=\"$namespace\"}[5m]))",
       "legendFormat": "Read"
      }
     ]
    },
    {
     "title": "Throughput",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum without (instance, ceph_daemon) (irate(ceph_osd_op_w_in_bytes{namespace=\"$namespace\"}[5m]))",
       "legendFormat": "Write"
      },
      {
       "expr": "sum without (instance, ceph_daemon) (irate(ceph_osd_op_r_out_bytes{namespace=\"$namespace\"}[5m]))",
       "legendFormat": "Read"
      }
     ]
    },
    {
     "title": "Pool Bytes Recovered",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum((ceph_pool_num_bytes_recovered{namespace=\"$namespace\"}) *on (instance, pool_id) group_left(name)(ceph_pool_metadata{namespace=\"$namespace\"})) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Pool Objects Recovered",
     "type": "graph",
     "gridPos": { "h": 8, "w": 7, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without (instance, pool_id) ((ceph_pool_num_objects_recovered{namespace=\"$namespace\"}) *on (instance, pool_id) group_left(name)(ceph_pool_metadata{namespace=\"$namespace\"}))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Objects Per Pool",
     "type": "graph",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without (instance) ((ceph_pool_objects{namespace=\"$namespace\"}) *on (instance, pool_id) group_left(name)(ceph_pool_metadata{namespace=\"$namespace\"}))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Pool Quota Bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum without (instance) ((ceph_pool_quota_bytes{namespace=\"$namespace\"}) *on (instance, pool_id) group_left(name)(ceph_pool_metadata{namespace=\"$namespace\"}))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Pool Objects Quota",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without (instance) (ceph_pool_quota_objects{namespace=\"$namespace\"}) *on (instance, pool_id) group_left(name)(ceph_pool_metadata{namespace=\"$namespace\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "OSD Type Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count without (instance, ceph_daemon) (ceph_bluestore_commit_lat_count{namespace=\"$namespace\"})",
       "legendFormat": "BlueStore"
      },
      {
       "expr": "count without (instance, ceph_daemon) (ceph_filestore_journal_latency_count{namespace=\"$namespace\"})",
       "legendFormat": "FileStore"
      }
     ]
    }
   ]
  },
  {
   "title": "OBJECTS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Objects in the Cluster",
     "type": "graph",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without (instance, pool_id) (ceph_pool_objects{namespace=\"$namespace\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "PGs State",
     "type": "graph",
     "gridPos": { "h": 12, "w": 8, "x": 6, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_active{namespace=\"$namespace\"})",
       "legendFormat": "Active"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_clean{namespace=\"$namespace\"})",
       "legendFormat": "Clean"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_peering{namespace=\"$namespace\"})",
       "legendFormat": "Peering"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_degraded{namespace=\"$namespace\"})",
       "legendFormat": "Degraded"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_stale{namespace=\"$namespace\"})",
       "legendFormat": "Stale"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_unclean_pgs{namespace=\"$namespace\"})",
       "legendFormat": "Unclean"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_undersized{namespace=\"$namespace\"})",
       "legendFormat": "Undersized"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_incomplete{namespace=\"$namespace\"})",
       "legendFormat": "Incomplete"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_forced_backfill{namespace=\"$namespace\"})",
       "legendFormat": "Forced Backfill"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_inconsistent{namespace=\"$namespace\"})",
       "legendFormat": "Inconsistent"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_forced_recovery{namespace=\"$namespace\"})",
       "legendFormat": "Forced Recovery"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_creating{namespace=\"$namespace\"})",
       "legendFormat": "Creating"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_wait_backfill{namespace=\"$namespace\"})",
       "legendFormat": "Wait Backfill"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_deep{namespace=\"$namespace\"})",
       "legendFormat": "Deep"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_scrubbing{namespace=\"$namespace\"})",
       "legendFormat": "Scrubbing"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_recovering{namespace=\"$namespace\"})",
       "legendFormat": "Recovering"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_repair{namespace=\"$namespace\"})",
       "legendFormat": "Repair"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_down{namespace=\"$namespace\"})",
       "legendFormat": "Down"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_peered{namespace=\"$namespace\"})",
       "legendFormat": "Peered"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_backfill{namespace=\"$namespace\"})",
       "legendFormat": "Backfill"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_remapped{namespace=\"$namespace\"})",
       "legendFormat": "Remapped"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_backfill_toofull{namespace=\"$namespace\"})",
       "legendFormat": "Backfill Toofull"
      }
     ]
    },
    {
     "title": "Stuck PGs",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_degraded{namespace=\"$namespace\"})",
       "legendFormat": "Degraded"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_stale{namespace=\"$namespace\"})",
       "legendFormat": "Stale"
      },
      {
       "expr": "sum without (instance, pool_id) (ceph_pg_undersized{namespace=\"$namespace\"})",
       "legendFormat": "Undersized"
      }
     ]
    },
    {
     "title": "Recovery Operations",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum without (instance, ceph_daemon) (irate(ceph_osd_recovery_ops{namespace=\"$namespace\"}[$interval]))",
       "legendFormat": "OPS"
      }
     ]
    }
   ]
  },
  {
   "title": "LATENCY",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "OSD Apply Latency Distribution",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "ceph_osd_apply_latency_ms{namespace=\"$namespace\"}"
      }
     ]
    },
    {
     "title": "OSD Commit Latency Distribution",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "expr": "ceph_osd_commit_latency_ms{namespace=\"$namespace\"}"
      }
     ]
    },
    {
     "title": "OSD Read Op Latency Distribution",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "rate(ceph_osd_op_r_latency_sum{namespace=\"$namespace\"}[5m]) / rate(ceph_osd_op_r_latency_count{namespace=\"$namespace\"}[5m]) >= 0"
      }
     ]
    },
    {
     "title": "OSD Write Op Latency Distribution",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "expr": "rate(ceph_osd_op_w_latency_sum{namespace=\"$namespace\"}[5m]) / rate(ceph_osd_op_w_latency_count{namespace=\"$namespace\"}[5m]) >= 0"
      }
     ]
    },
    {
     "title": "Avg OSD  Op  Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg without (instance,ceph_daemon) (rate(ceph_osd_op_r_latency_sum{namespace=\"$namespace\"}[5m]) / rate(ceph_osd_op_r_latency_count{namespace=\"$namespace\"}[5m]) >= 0)",
       "legendFormat": "read"
      },
      {
       "expr": "avg without (instance, ceph_daemon) (rate(ceph_osd_op_w_latency_sum{namespace=\"$namespace\"}[5m]) / rate(ceph_osd_op_w_latency_count{namespace=\"$namespace\"}[5m]) >= 0)",
       "legendFormat": "write"
      }
     ]
    },
    {
     "title": "AVG OSD Apply + Commit Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "avg without (instance, ceph_daemon) (ceph_osd_apply_latency_ms{namespace=\"$namespace\"})",
       "legendFormat": "apply"
      },
      {
       "expr": "avg without (instance, ceph_daemon) (ceph_osd_commit_latency_ms{namespace=\"$namespace\"})",
       "legendFormat": "commit"
      }
     ]
    }
   ]
  },
  { "title": "Node Statistics (NodeExporter)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Node Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Active_anon_bytes{namespace=\"$namespace\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum without (instance) (node_memory_Active_anon_bytes{namespace=\"$namespace\"})",
     "legendFormat": "Cluster Memory Usage"
    }
   ]
  },
  {
   "title": "Node CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg by (instance) (irate(node_cpu_seconds_total{namespace=\"$namespace\",mode!=\"idle\"}[$interval])) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node Out",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_disk_read_bytes_total{namespace=\"$namespace\"}[$interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node In",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(irate(node_disk_written_bytes_total{namespace=\"$namespace\"}[$interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Free Space in root filesystem",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_free_bytes{namespace=\"$namespace\", mountpoint='/', device != 'rootfs'})*100 / (node_filesystem_size_bytes{namespace=\"$namespace\", mountpoint='/', device != 'rootfs'})",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}