apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: teleport-enterprise-license-m5bffgtbh6
  namespace: teleport
  files:
  - license.pem
- name: teleport-general-secret-20210310
  namespace: teleport
  files:
  - teleport.yaml
patches:
- patch: |-
    apiVersion: v1
    kind: Secret
    metadata:
      name: teleport-general-secret-20210310
      namespace: teleport
      labels:
        app.kubernetes.io/name: teleport
generatorOptions:
  disableNameSuffixHash: true
