apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - toolbox.yaml
images:
  - name: rook/ceph
    newName: quay.io/cybozu/rook
    newTag: 1.5.7.2
patchesJSON6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: rook-ceph-tools
    namespace: rook-ceph
  # Tools pod depends ConfigMap made by Rook, so that it should be created after CephCluster
  patch: |-
    - op: add
      path: /metadata/annotations
      value: { "argocd.argoproj.io/sync-wave": "1" }
